[build.environment]
  NPM_FLAGS = "--prefix=/dev/null"
[build]
  publish = "public"
  command = "npx pnpm i --store=node_modules/.pnpm-store && npx pnpm run build"

[[plugins]]
     package = "./plugins/pnpm-preinstaller"